services:
  web:
    build: ./backend
    environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/proyectos
        - SPRING_DATASOURCE_DRIVERCLASSNAME=com.mysql.cj.jdbc.Driver
        - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQLDialect
        - SPRING_DATASOURCE_USERNAME=desarrollador
        - SPRING_DATASOURCE_PASSWORD=dlpd
    ports:
        - "8080:8080"
    restart: always
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: "mysql:8.4.0"
    environment:
        - MYSQL_ROOT_PASSWORD=rootpassword
        - MYSQL_DATABASE=proyectos
        - MYSQL_USER=desarrollador
        - MYSQL_PASSWORD=dlpd
    volumes:
        - "datos:/var/lib/mysql"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
    datos:
